<a href="https://colab.research.google.com/github/PierDiella/BigData_Rep/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import random

In [3]:
df=pd.read_csv("student_prediction.csv")

df.head(10)

STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [5]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)

[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.

In [6]:
print(X2.shape)
print(Y2.shape)

(145, 30)
(145, 1)


Squared normalization

In [8]:
X = normalize(X2, norm='l2')

print(X)

[[0.1796053  0.1796053  0.26940795 ... 0.1796053  0.08980265 0.08980265]
 [0.18490007 0.18490007 0.2773501  ... 0.18490007 0.18490007 0.2773501 ]
 [0.1933473  0.1933473  0.1933473  ... 0.09667365 0.1933473  0.1933473 ]
 ...
 [0.07881104 0.07881104 0.07881104 ... 0.07881104 0.31524416 0.23643312]
 [0.14948702 0.07474351 0.14948702 ... 0.07474351 0.37371755 0.22423053]
 [0.07254763 0.07254763 0.07254763 ... 0.07254763 0.36273813 0.2901905 ]]


MinMax regularization

In [9]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

y1 = scaler.fit_transform(Y2)
Yk = np.ravel(y1)                                                                   # Appiattisce y
y = np.where(Yk < 18, 0, 1)
print(X)
print(y1)
print(y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[[ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857

In [10]:
print(X.shape)
print(y.shape)

(145, 30)
(145,)


# Logistic Regression

In [11]:
def sig(x):
 return 1/(1 + np.exp(-x))

In [26]:
def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost


W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
b = 0


total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={} and W=1, total_cost={}'.format(b,total_cost))


for b=0 and W=1, total_cost=nan


<ipython-input-26-9f34e6464b81>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-26-9f34e6464b81>:9: RuntimeWarning: invalid value encountered in double_scalars
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


In [24]:
def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost


#W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
W = np.random.randn(30)
#b = 0
b = random.uniform(-5, 5)


total_cost = compute_multiple_cost(X, y, W, b)


print ('for b={} and W={} randomic, total_cost={}'.format(b,W,total_cost))

for b=3.8676627213343515 and W=[ 0.13316524  0.67671415 -0.26668199 -0.41480974  0.82031102 -1.96623707
  1.2821863   0.79732511  0.64439837  0.46172848 -0.03968079  0.07074566
  0.03340453 -1.13004681  1.20877078 -0.67726731 -1.68360389  0.30150624
  0.1764363   1.60856791  1.01735211 -0.04452244 -0.29974584  0.64517833
 -0.34417475 -0.4629999   0.58025942  0.91781123 -1.41725524 -0.123173  ] randomic, total_cost=inf


<ipython-input-24-4dbdca3af6d0>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


In [27]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)

print ('for b={} and W={} randomic, \n dj_dW={} \n dj_db={}'.format(b,W,dj_dW,dj_db))

[2.24137931 3.44827586 3.         4.29310345 4.06896552 4.27586207
 4.06896552 1.29310345 1.56321839 1.54022989 1.68275862 2.12413793
 2.93103448 0.48275862 2.34482759 3.03448276 2.0862069  2.96551724
 3.37931034 1.72413793 0.96551724 1.79310345 1.13793103 0.55172414
 5.17241379 3.48275862 4.62068966 2.55172414 3.22413793 3.6091954 ] 0.6758620689655183
for b=0 and W=[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.] randomic, 
 dj_dW=[2.24137931 3.44827586 3.         4.29310345 4.06896552 4.27586207
 4.06896552 1.29310345 1.56321839 1.54022989 1.68275862 2.12413793
 2.93103448 0.48275862 2.34482759 3.03448276 2.0862069  2.96551724
 3.37931034 1.72413793 0.96551724 1.79310345 1.13793103 0.55172414
 5.17241379 3.48275862 4.62068966 2.55172414 3.22413793 3.6091954 ] 
 dj_db=0.6758620689655183


In [28]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}),\n cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = W
b_in = b

alpha = 0.008
num_iters = 10000

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)


<ipython-input-26-9f34e6464b81>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-26-9f34e6464b81>:9: RuntimeWarning: invalid value encountered in double_scalars
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 0: (w,b) = ([0.98206897 0.97241379 0.976      0.96565517 0.96744828 0.9657931
 0.96744828 0.98965517 0.98749425 0.98767816 0.98653793 0.9830069
 0.97655172 0.99613793 0.98124138 0.97572414 0.98331034 0.97627586
 0.97296552 0.9862069  0.99227586 0.98565517 0.99089655 0.99558621
 0.95862069 0.97213793 0.96303448 0.97958621 0.9742069  0.97112644], -0.005406896551724146),
 cost = nan
Iteration 100: (w,b) = ([ 0.08307334  0.21658729  0.09924139 -0.36581953  0.06137508 -0.25317593
 -0.19989126  0.27115389  0.22890925  0.36396543  0.31827684  0.22344434
  0.23500984  0.66643482  0.05245405 -0.03114937  0.22372321  0.07785032
 -0.13497357  0.20220314  0.37169035  0.14999817  0.36471797  0.70030988
 -0.58635959 -0.11076374 -0.34769956  0.23336529  0.15998847 -0.06206267], -0.22976075611859034),
 cost = 0.9024363837745891
Iteration 200: (w,b) = ([-0.15098528  0.23844947  0.18574438 -0.31420002  0.18557019 -0.18312409
 -0.05003461 -0.05106861  0.00657492  0.30779095  0.13999306  0.06744

(array([-0.31416528,  0.1373377 ,  0.2077645 , -0.20986907,  0.17811024,
        -0.03879069, -0.00195369, -0.3863779 , -0.13822176,  0.3215975 ,
         0.04533043, -0.04959685,  0.05038686,  0.21506313, -0.33709159,
        -0.1476007 , -0.16550278,  0.24612349,  0.03553574, -0.05766193,
        -0.28804796,  0.0158595 ,  0.0991044 , -0.05134376, -0.07224667,
         0.02297883, -0.11298198, -0.01734981,  0.32474746, -0.07883646]),
 -0.8038999656268877,
 0.20062131536495195)